org: dremdem
app: kbb
service: kanban-board-backend

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

  stage: dev
  region: eu-central-1

  environment:
    KANBAN_BOARD_STAGE: 'prod'

functions:
  new:
    handler: task/new_task.new_task_handler
    events:
      - http:
          path: new
          method: post
  start:
    handler: task/start_task.start_task_handler
    events:
      - http:
          path: start
          method: post
  get_elapsed_time:
    handler: task/start_task.get_elapsed_time_handler
    events:
      - http:
          path: get_elapsed_time
          method: post
  resolve:
    handler: task/resolve_task.resolve_task_handler
    events:
      - http:
          path: resolve
          method: post
  get_cost:
    handler: task/resolve_task.get_cost_handler
    events:
      - http:
          path: get_cost
          method: post
  get_tasks:
    handler: task/tasks.get_tasks_handler
    events:
      - http:
          path: tasks
          method: post
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
