version: "3.9"

services:
  db:
    image: postgres:13.3
    env_file:
      - postgres_config.env
    restart: always
    ports:
      - "5432:5432"
    networks:
      - test
    hostname: test_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  test:


